---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: aspireitconf.azurecr.io/metricsapp:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: app-env
      imagePullSecrets:
      - name: acr-registry
      terminationGracePeriodSeconds: 180